from django.db import models

# Create your models here.
class form1Detail(models.Model):
    Dialer_Name=models.CharField(max_length=300)
    Describe_call=models.TextField(max_length=500)
    Incident_Type=models.CharField(max_length=500)
    Phone_Number=models.CharField(max_length=20)
    District=models.CharField(max_length=500)
    Incident_Address=models.TextField(max_length=500)
    frv_req=models.CharField(max_length=100)
    City=models.CharField(max_length=100)
    State=models.CharField(max_length=100)
    Country=models.CharField(max_length=100)
    Pin_Code=models.CharField(max_length=7)
    date = models.DateField()
    lat=models.CharField(max_length=50, default='')
    lng=models.CharField(max_length=50, default='')

class FRV(models.Model):
    FRV_Type=models.CharField(max_length=20)
    Driver_Name=models.CharField(max_length=100)
    lat=models.CharField(max_length=50, default='')
    lng=models.CharField(max_length=50, default='')

class FRV_Assigned(models.Model):
    FRV_Type=models.CharField(max_length=20)
    Driver_Name=models.CharField(max_length=100)
    lat=models.CharField(max_length=50, default='')
    lng=models.CharField(max_length=50, default='')
    case_id=models.CharField(max_length=50)
    end_lat=models.CharField(max_length=50, default='')
    end_lng=models.CharField(max_length=50, default='')
    status=models.CharField(max_length=50, default='assigned')
    waypoints=models.TextField(max_length=1000, default='')

class Operations(models.Model):
    id=models.BigIntegerField(primary_key=True)
    Dialer_Name=models.CharField(max_length=300)
    Describe_call=models.TextField(max_length=500)
    Incident_Type=models.CharField(max_length=500)
    Phone_Number=models.CharField(max_length=20)
    District=models.CharField(max_length=500)
    Incident_Address=models.TextField(max_length=500)
    City=models.CharField(max_length=100)
    State=models.CharField(max_length=100)
    Country=models.CharField(max_length=100)
    Pin_Code=models.CharField(max_length=7)
    frvs=models.ManyToManyField(FRV, blank=True)
    date = models.DateField()
    lat=models.CharField(max_length=50, default='')
    lng=models.CharField(max_length=50, default='')

class History(models.Model):
    id=models.BigIntegerField(primary_key=True)
    Dialer_Name=models.CharField(max_length=300)
    Describe_call=models.TextField(max_length=500)
    Incident_Type=models.CharField(max_length=500)
    Phone_Number=models.CharField(max_length=20)
    District=models.CharField(max_length=500)
    Incident_Address=models.TextField(max_length=500)
    City=models.CharField(max_length=100)
    State=models.CharField(max_length=100)
    Country=models.CharField(max_length=100)
    Pin_Code=models.CharField(max_length=7)
    frvs=models.ManyToManyField(FRV, blank=True)
    date = models.DateField()
    lat=models.CharField(max_length=50, default='')
    lng=models.CharField(max_length=50, default='')