# Generated by Django 4.1 on 2022-08-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form1Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dialer_Name', models.CharField(max_length=300)),
                ('Dialer_Address', models.TextField(max_length=500)),
                ('Describe_call', models.TextField(max_length=500)),
                ('Incident_Type', models.CharField(max_length=500)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Division', models.CharField(max_length=500)),
                ('District', models.CharField(max_length=500)),
                ('Incident_Address', models.TextField(max_length=500)),
                ('date', models.DateTimeField())
            ],
        ),
    ]
