# Generated by Django 4.1 on 2022-08-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1detail',
            name='date',
            field=models.DateField(),
        ),
    ]
