# Generated by Django 4.1 on 2022-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_alter_form1detail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1detail',
            name='frv_req',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
