# Generated by Django 4.1 on 2022-08-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0004_frv_operations_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='frv',
            name='lat',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frv',
            name='lng',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form1detail',
            name='Phone_Number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='Phone_Number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operations',
            name='Phone_Number',
            field=models.CharField(max_length=20),
        ),
    ]
