# Generated by Django 4.1 on 2022-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0006_form1detail_lat_form1detail_lng_history_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1detail',
            name='lat',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='form1detail',
            name='lng',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='frv',
            name='lat',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='frv',
            name='lng',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='lat',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='lng',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='operations',
            name='lat',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='operations',
            name='lng',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
