# Generated by Django 4.1 on 2022-08-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0006_remove_frv_driver_number_remove_frv_frv_plate_no_and_more'),
        ('form1', '0007_alter_form1detail_lat_alter_form1detail_lng_and_more'),
    ]

    operations = [
    ]
