# Generated by Django 4.1 on 2022-08-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0009_frv_assigned_remove_frv_end_lat_remove_frv_end_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frv_assigned',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
