# Generated by Django 4.1 on 2022-08-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0010_frv_assigned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='frv_assigned',
            name='waypoints',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='frv_assigned',
            name='status',
            field=models.CharField(default='assigned', max_length=50),
        ),
    ]
