# Generated by Django 4.1 on 2022-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0012_frv_draw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1detail',
            name='Dialer_Address',
        ),
        migrations.RemoveField(
            model_name='form1detail',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Dialer_Address',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='Dialer_Address',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='Division',
        ),
        migrations.AddField(
            model_name='form1detail',
            name='City',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form1detail',
            name='Country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form1detail',
            name='Pin_Code',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form1detail',
            name='State',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='City',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='Country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='Pin_Code',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='State',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='City',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='Country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='Pin_Code',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='State',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
